[package]
name = "rackfan_daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
rppal = "0.22.1"
syslog = "7.0.0"
ctrlc = "3.2.1"
log = "0.4.26"
libc = "0.2.170"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
glob = "0.3"

